SinExWebApp20444290/Models/Invoice.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SinExWebApp20444290.Models
{
    [Table("Payment")]
    public class Invoice
    {
        [Key]
        [Required]
        public virtual int PaymentID { get; set; }
        [Required]
        public virtual string AuthorizationCode { get; set; }
        [Required]
        public virtual int WaybillID { get; set; }
        public virtual decimal PaymentAmount { get; set; }
        public virtual string CurrencyCode { get; set; }
        public virtual string UserName { get; set; }
        public virtual string PayerCharacter { get; set; }
        public virtual string PaymentDescription { get; set; }

        [ForeignKey("WaybillID")]
        public virtual Shipment Shipment { get; set; }

    }
}

SinExWebApp20444290/Controllers/InvoicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using SinExWebApp20444290.Models;
using X.PagedList;
using SinExWebApp20444290.ViewModels;

namespace SinExWebApp20444290.Controllers
{
    public class InvoicesController : Controller
    {
        private SinExDatabaseContext db = new SinExDatabaseContext();
        
        //Get : Payments/GeneratePaymentHistory
        public ActionResult GeneratePaymentHistoryReport(
            int? ShippingAccountId,
            DateTime? StartingDate,
            DateTime? EndingDate,
            string sortOrder,
            int? currentShippingAccountId,
            DateTime? currentStartingDate,
            DateTime? currentEndingDate,
            int? page)
        {

            if (ShippingAccountId == null)
            {
                ShippingAccountId = currentShippingAccountId;
            }

            // Instantiate an instance of the PaymentsReportViewModel and the PaymentsSearchViewModel.
            var PaymentReport = new PaymentsReportViewModel();
            PaymentReport.PaymentSearch = new PaymentsSearchViewModel();

            // Code for paging.
            ViewBag.CurrentSort = sortOrder;
            int pageSize = 5;
            int pageNumber = (page ?? 1);

            // Retain search conditions for sorting.
            if (StartingDate == null)
            {
                StartingDate = currentStartingDate;
            }
            if (EndingDate == null)
            {
                EndingDate = currentEndingDate;
            }
            if (ShippingAccountId == null)
            {
                ShippingAccountId = currentShippingAccountId;
            }
            else
            {
                page = 1;
            }
            ViewBag.CurrentShippingAccountId = ShippingAccountId;
            ViewBag.CurrentStartingDate = StartingDate;
            ViewBag.CurrentEndingDate = EndingDate;


            // Populate the ShippingAccountId dropdown list.
            var shippingAccountQuery = db.Invoices.Select(s => s.UserName).Distinct().OrderBy(s => s);
            var hehe = db.ShippingAccounts.Where(m => shippingAccountQuery.Contains(m.UserName)).Select(m => m.ShippingAccountID).Distinct().OrderBy(m => m);


            var n = (new SelectList(hehe)).ToList() ;
            foreach (SelectListItem k in n)
            {
                k.Value = k.Text;
            }
            n.Insert(0, new SelectListItem
            {
                Text = "All",
                Value = "0"
            });
            int haha = 0;
            for (int i = 0; i < n.Count(); i++)
            {
                if (n.ElementAt(i).Value == ShippingAccountId.ToString())
                {
                    haha = i;
                    break;
                }
            }
            foreach (var item in n)
            {
                if (item.Value == ShippingAccountId.ToString())
                {
                    item.Selected = true;
                }
            }
            PaymentReport.PaymentSearch.ShippingAccounts = n;
            PaymentReport.PaymentSearch.ShippingAccountId = ShippingAccountId == null ? 0 : (int)ShippingAccountId;
            //Initialize the query to retrieve payments using the PaymentsListViewModel.
            var list = new List<PaymentsListViewModel>();
            foreach (Invoice v in db.Invoices)
            {
                PaymentsListViewModel m = new PaymentsListViewModel();
                Shipment ship = db.Shipments.Where(a => a.WaybillID == v.WaybillID).First();
                m.WaybillId = v.WaybillID;
                m.ShippingAccountId = v.PayerCharacter == "Recipient" ? ship.RecipientShippingAccountID : ship.ShippingAccountID;
                m.ShipDate = (DateTime)ship.PickupDate;
                m.RecipientName = ship.RecipientName;
                m.OriginCity = ship.Origin;
                m.DestinationCity = ship.Destination;
                m.ServiceType = db.ServiceTypes.Single(a => a.Type == ship.ServiceType).Type;
                m.TotalPaymentAmount = v.PaymentAmount;
                m.PaymentDescription = v.PaymentDescription;
                list.Add(m);
            }
            var paymentQuery = list.AsQueryable();
            // Add the condition to select a spefic shipping account if shipping account id is not null.
            if (ShippingAccountId != 0 && ShippingAccountId != null)
            {
                // TODO: Construct the LINQ query to retrive only the shipments for the specified shipping account id.
                paymentQuery = paymentQuery.Where(s => s.ShippingAccountId == ShippingAccountId);

            }

            if ((StartingDate != null) && (EndingDate != null))
            {
                paymentQuery = paymentQuery.Where(s => (s.ShipDate > StartingDate && s.ShipDate < EndingDate));
            }
            else
            {
                // Return an empty result if no shipping account id has been selected.
                PaymentReport.PaymentList = new PaymentsListViewModel[0].ToPagedList(pageNumber, pageSize);
            }

            // Code for sorting on ServiceType, ShippedDate, DeliveredDate, RecipientName, Origin, Destination
            ViewBag.ServiceTypeSortParm = sortOrder == "serviceType" ? "serviceType_desc" : "serviceType";
            ViewBag.ShippedDateSortParm = sortOrder == "shippedDate" ? "shippedDate_desc" : "shippedDate";
            ViewBag.RecipientNameSortParm = sortOrder == "recipientName" ? "recipientName_desc" : "recipientName";
            ViewBag.OriginSortParm = sortOrder == "origin" ? "origin_desc" : "origin";
            ViewBag.DestinationSortParm = sortOrder == "destination" ? "destination_desc" : "destination";
            ViewBag.InvoiceAmountSortParm = sortOrder == "invoiceAmount" ? "invoiceAmount_desc" : "invoiceAmount";
            switch (sortOrder)
            {
                case "serviceType_desc":
                    paymentQuery = paymentQuery.OrderByDescending(s => s.ServiceType);
                    break;
                case "serviceType":
                    paymentQuery = paymentQuery.OrderBy(s => s.ServiceType);
                    break;
                case "shippedDate_desc":
                    paymentQuery = paymentQuery.OrderByDescending(s => s.ShipDate);
                    break;
                case "shippedDate":
                    paymentQuery = paymentQuery.OrderBy(s => s.ShipDate);
                    break;
                case "recipientName_desc":
                    paymentQuery = paymentQuery.OrderByDescending(s => s.RecipientName);
                    break;
                case "recipientName":
                    paymentQuery = paymentQuery.OrderBy(s => s.RecipientName);
                    break;
                case "origin_desc":
                    paymentQuery = paymentQuery.OrderByDescending(s => s.OriginCity);
                    break;
                case "origin":
                    paymentQuery = paymentQuery.OrderBy(s => s.OriginCity);
                    break;
                case "destination_desc":
                    paymentQuery = paymentQuery.OrderByDescending(s => s.DestinationCity);
                    break;
                case "destination":
                    paymentQuery = paymentQuery.OrderBy(s => s.DestinationCity);
                    break;
                case "invoiceAmount_desc":
                    paymentQuery = paymentQuery.OrderByDescending(s => s.TotalPaymentAmount);
                    break;
                case "invoiceAmount":
                    paymentQuery = paymentQuery.OrderBy(s => s.TotalPaymentAmount);
                    break;
                default:
                    paymentQuery = paymentQuery.OrderBy(s => s.WaybillId);
                    break;
            }
            PaymentReport.PaymentList = paymentQuery.ToPagedList(pageNumber, pageSize);
            return View(PaymentReport);
        }

        public void CreateInvoice(int WaybillID)
        {
            var q = from s in db.Shipments select s;
            q = q.Where(x => x.WaybillID == WaybillID);
            var holder = q.ToList()[0];

            var a = from s in db.ShippingAccounts select s;
            a = a.Where(s => s.ShippingAccountID == holder.ShippingAccountID);

            PersonalShippingAccount psa = (PersonalShippingAccount) a.ToList()[0];

            int authorizationCode = BaseController.AuthorizeCreditCard(psa.ccNumber, psa.ccSecurityNumber, holder.ShipmentAmount);

            Invoice invoice = new Invoice();
            invoice.AuthorizationCode = authorizationCode.ToString();

            var n = from s in db.Packages select s;
            n = n.Where(x => x.WaybillID == WaybillID);
            foreach(var item in n.ToList())
            {
                invoice.CurrencyCode = item.CurrencyCode;
                break;
            }
            invoice.PayerCharacter = holder.ShipmentPayer ? psa.FirstName + " " + psa.LastName : holder.RecipientName;
            invoice.PaymentAmount = holder.ShipmentAmount;
            invoice.WaybillID = WaybillID;
            invoice.UserName = psa.UserName;

            //string email = holder.ShipmentPayer ? psa.Email : holder.RecipientEmail;

            string html = "";
            html = html + "<p>Hello " + invoice.PayerCharacter + ",</p>";
            html = html + "<p>Here is the invoice for Shipment: " + invoice.WaybillID + "</p>";
            html = html + "<p>Invoice payer: " + invoice.PayerCharacter + "</p>";
            html = html + "<p>Shipment waybill number: " + invoice.WaybillID + "</p>";
            html = html + "<p>Ship date: " + holder.PickupDate + "</p>";
            html = html + "<p>Service type: " + holder.ServiceType + "</p>";

SinExWebApp20444290/Views/Invoices/Create.cshtml
@model SinExWebApp20444290.Models.Invoice

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Invoice</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.AuthorizationCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AuthorizationCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AuthorizationCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WaybillID, "WaybillID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("WaybillID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.WaybillID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaymentAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaymentAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaymentAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CurrencyCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CurrencyCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CurrencyCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PayerCharacter, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PayerCharacter, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PayerCharacter, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaymentDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaymentDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaymentDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SinExWebApp20444290/Views/Invoices/Delete.cshtml
@model SinExWebApp20444290.Models.Invoice

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Invoice</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Shipment.ReferenceNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Shipment.ReferenceNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AuthorizationCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuthorizationCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurrencyCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrencyCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PayerCharacter)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PayerCharacter)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentDescription)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SinExWebApp20444290/Views/Invoices/Details.cshtml
@model SinExWebApp20444290.Models.Invoice

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Invoice</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Shipment.ReferenceNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Shipment.ReferenceNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AuthorizationCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuthorizationCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurrencyCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrencyCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PayerCharacter)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PayerCharacter)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentDescription)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PaymentID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SinExWebApp20444290/Views/Invoices/Edit.cshtml
@model SinExWebApp20444290.Models.Invoice

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Invoice</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PaymentID)

        <div class="form-group">
            @Html.LabelFor(model => model.AuthorizationCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AuthorizationCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AuthorizationCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WaybillID, "WaybillID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("WaybillID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.WaybillID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaymentAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaymentAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaymentAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CurrencyCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CurrencyCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CurrencyCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PayerCharacter, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PayerCharacter, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PayerCharacter, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaymentDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaymentDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaymentDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SinExWebApp20444290/Views/Invoices/GeneratePaimentHistoryReport.cshtml
@model SinExWebApp20444290.ViewModels.PaymentsReportViewModel

@{
    ViewBag.Title = "Generate Invoice History";
}

<h2>Invoice History</h2>
<hr />
@Html.Partial("_PaymentsSearchPartial", Model.PaymentSearch)
@Html.Partial("_PaymentsListPartial", Model.PaymentList)
@Html.Partial("_PaymentsReportViewPagingPartial", Model.PaymentList)

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/jquery-ui-timepicker-addon.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $(function () {
                $(".date-time-picker").datetimepicker({
                    changeMonth: true,
                    changeYear: true,
                    yearRange: "-100:+0",
                    dateFormat: 'yy/mm/dd',
                    controlType: 'select',
                    timeFormat: 'HH:mm'
                });
            });

            jQuery.validator.methods.date = function (value, element) {
                var isChrome = /Chrome/.test(navigator.userAgent) && /Google Inc/.test(navigator.vendor);
                if (isChrome) {
                    var d = new Date();
                    return this.optional(element) || !/Invalid|NaN/.test(new Date(d.toLocaleDateString(value)));
                } else {
                    return this.optional(element) || !/Invalid|NaN/.test(new Date(value));
                }
            };
        });
    </script>
}

SinExWebApp20444290/Views/Invoices/GeneratePaymentHistoryReport.cshtml
@model SinExWebApp20444290.ViewModels.PaymentsReportViewModel

@{
    ViewBag.Title = "Generate Invoice History";
}

<h2>Invoice History</h2>
<hr />
@Html.Partial("_PaymentSearchPartial", Model.PaymentSearch)
@Html.Partial("_PaymentsListPartial", Model.PaymentList)
@Html.Partial("_PaymentReportViewPagingPartial", Model.PaymentList)

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/jquery-ui-timepicker-addon.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $(function () {
                $(".date-time-picker").datetimepicker({
                    changeMonth: true,
                    changeYear: true,
                    yearRange: "-100:+0",
                    dateFormat: 'yy/mm/dd',
                    controlType: 'select',
                    timeFormat: 'HH:mm'
                });
            });

            jQuery.validator.methods.date = function (value, element) {
                var isChrome = /Chrome/.test(navigator.userAgent) && /Google Inc/.test(navigator.vendor);
                if (isChrome) {
                    var d = new Date();
                    return this.optional(element) || !/Invalid|NaN/.test(new Date(d.toLocaleDateString(value)));
                } else {
                    return this.optional(element) || !/Invalid|NaN/.test(new Date(value));
                }
            };
        });
    </script>
}

SinExWebApp20444290/Views/Invoices/Index.cshtml
@model IEnumerable<SinExWebApp20444290.Models.Invoice>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Shipment.ReferenceNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AuthorizationCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PaymentAmount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CurrencyCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PayerCharacter)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PaymentDescription)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Shipment.ReferenceNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AuthorizationCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PaymentAmount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CurrencyCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PayerCharacter)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PaymentDescription)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PaymentID }) |
            @Html.ActionLink("Details", "Details", new { id=item.PaymentID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PaymentID })
        </td>
    </tr>
}

</table>

SinExWebApp20444290/Views/Invoices/_PaymentSearchPartial.cshtml
@model SinExWebApp20444290.ViewModels.PaymentsSearchViewModel

@using (Html.BeginForm("GeneratePaymentHistoryReport", "Invoices", FormMethod.Get))
{
    <div class="form-group">

        @if (User.IsInRole("Employee"))
        {
        <div class="col-md-12">
            @Html.LabelFor(a => a.ShippingAccountId, "Shipping Account: ")
            @Html.DropDownListFor(a => a.ShippingAccountId, Model.ShippingAccounts, new { @class = "form-control", @Value = ViewBag.CurrentShippingAccountId })
            @Html.ValidationMessageFor(a => a.ShippingAccountId, "", new { @class = "text-danger" })
        </div>
        }
        <div class="col-md-12">
            @Html.LabelFor(a => a.StartingDate, "Date from ")
            @Html.EditorFor(a => a.StartingDate, new { htmlAttributes = new { @class = "form-control date-time-picker", @Value = ViewBag.CurrentStartingDate != null ? ViewBag.CurrentStartingDate.ToString("yyyy/MM/dd HH:mm") : DateTime.Now.ToString("yyyy/MM/dd HH:mm") } })
            @Html.ValidationMessageFor(model => model.StartingDate, "", new { @class = "text-danger" })

            @Html.LabelFor(a => a.EndingDate, "To ")
            @Html.EditorFor(a => a.EndingDate, new { htmlAttributes = new { @class = "form-control date-time-picker", @Value = ViewBag.CurrentEndingDate != null ? ViewBag.CurrentEndingDate.ToString("yyyy/MM/dd HH:mm") : DateTime.Now.ToString("yyyy/MM/dd HH:mm") } })
            @Html.ValidationMessageFor(model => model.EndingDate, "", new { @class = "text-danger" })

            <input type="submit" value="Search" />
        </div>
    </div>
}